task-1-4

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,16 +8,13 @@ jobs:
     steps:
       - name: say hello.
         run: 
-        echo "Hello, world!"
+          echo "Hello, world!"
   echo-goodbye: 
     runs-on: ubuntu-latest
     steps:
       - name: success step
         run : |
-               echo "i will fail"    
-               exit 1
-      name: say goodbye
-      run: echo "Goodbye!"    
-
-              
-            
+          echo "i will fail"    
+          exit 1
+        name: say goodbye
+        run: echo "Goodbye!"          
